import Head from "next/head";
import "./globals.css";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import Navbar from "./component/navbar";

const inter = Inter({ subsets: ["latin"] });
const plexmono = IBM_Plex_Mono({ subsets: ["latin-ext"], weight: ["500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600;700&family=Kanit:wght@400;500;600;700&family=Lato:wght@400;700&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        {" "}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
